const canvas = document.getElementById("canvas");
const ctx = canvas.getContext("2d");

const fileInput = document.getElementById("inputFile");
const brightnessBtn = document.getElementById("brightness");
const contrastBtn = document.getElementById("contrast");
const saturationBtn = document.getElementById("saturation");
const blurBtn = document.getElementById("blur");

const grayScaleBtn = document.getElementById("grayScale");
const sepiaBtn = document.getElementById("sepia");
const resetBtn = document.getElementById("reset");

const downloadBtn = document.getElementById("downloadBtn");

let image = new Image(); // storing the uploaded image
let isSepia = false;

const ActiveBtnColor = "#98CA98";
const InactiveBtnColor = "#CAAA98";

fileInput.addEventListener("change", function(e){
    const file = e.target.files[0];
    console.log(file);
    if(!file) return;
    const reader = new FileReader();  //this is used to read the file and convert it into a data URL. its a web api that allows you to read the contents of files stored on the user's computer. it provides a way to asynchronously read the contents of files, which can be useful for tasks like uploading files or displaying images.

    reader.onload = () => {
        image.src = reader.result;  //this is used to set the source of the image element to the data URL that was generated by the FileReader. when the file is read successfully, the onload event is triggered, and the result property of the FileReader contains the data URL representing the file's contents. by setting image.src to reader.result, we can display the uploaded image on the webpage.
    };
    reader.readAsDataURL(file);  //this is used to start reading the file as a data URL. when this method is called, the FileReader will read the contents of the specified file and convert it into a data URL format. once the reading process is complete, the onload event will be triggered, allowing us to access the resulting data URL through the reader.result property.
});

image.onload = () => {
    canvas.height = image.height;
    canvas.width = image.width;
    ctx.drawImage(image, 0, 0, canvas.width, canvas.height);
}

function applyBrightnessFilter(){
    const brightnessValue = brightnessBtn.value;
    const saturationValue = saturationBtn.value;
    const contrastValue = contrastBtn.value;
    const blurValue = blurBtn.value;
    const sepiaValue = isSepia ? 100 : 0;
    ctx.filter = `brightness(${brightnessValue}%)
              saturate(${saturationValue}%)
              contrast(${contrastValue}%)
              blur(${blurValue}px)
              sepia(${sepiaValue}%)`;
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    ctx.drawImage(image, 0, 0, canvas.width, canvas.height);
    if(saturationValue == 0){
        grayScaleBtn.style.backgroundColor = ActiveBtnColor;
    } else {
        grayScaleBtn.style.backgroundColor = InactiveBtnColor;
    }

}

brightnessBtn.addEventListener("input", applyBrightnessFilter);

saturationBtn.addEventListener("input", applyBrightnessFilter);

contrastBtn.addEventListener("input", applyBrightnessFilter);

blurBtn.addEventListener("input", applyBrightnessFilter);

resetBtn.addEventListener("click", () => {
    brightnessBtn.value = 100;
    saturationBtn.value = 100;
    contrastBtn.value = 100;
    blurBtn.value = 0;
    if(isSepia){
        handleSepia();
    }
    applyBrightnessFilter();
})

grayScaleBtn.addEventListener("click", () => {
    saturationBtn.value = 0;
    applyBrightnessFilter();
})

function handleSepia(){
    isSepia = !isSepia;
    applyBrightnessFilter();
    if(isSepia){
        sepiaBtn.style.backgroundColor = ActiveBtnColor;
    } else {
        sepiaBtn.style.backgroundColor = InactiveBtnColor;
    }
}

sepiaBtn.addEventListener("click", handleSepia);

downloadBtn.addEventListener("click", () => {
    const imageData = canvas.toDataURL("image/png");// canvas into image and then to url
    const anchorTag = document.createElement("a");
    anchorTag.href = imageData;
    anchorTag.download = "Photon-Lab.png";
    document.body.appendChild(anchorTag);
    anchorTag.click();
    document.body.removeChild(anchorTag);
});